name: CI

on: [push]

jobs:
  macos:
    runs-on: macOS-latest

    strategy:
      matrix:
        destination:
          - platform=macOS
          - platform=iOS Simulator,name=iPhone 11

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Generate Xcode Project
        run: swift package generate-xcodeproj
      - name: Run Test Target
        run: xcodebuild test -destination '${{ matrix.destination }}' -scheme HypertextLiteral-Package

  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        swift: ["5.1"]

    container:
      image: swift:${{ matrix.swift }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery
